# Generated by Django 5.0.6 on 2024-07-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='service_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='service_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
