# Generated by Django 5.1 on 2024-09-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='report_detail',
            new_name='report_description',
        ),
    ]
