# Generated by Django 5.1 on 2024-09-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_report_detail_workorder_report_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='service_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Término do Serviço'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='service_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Início do Serviço'),
        ),
    ]
