# Generated by Django 5.1 on 2024-09-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_workorder_dept_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='resposible_employee',
            new_name='responsible_employee',
        ),
    ]
