# Generated by Django 5.1 on 2024-09-07 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_workorder_dept_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='order_type',
        ),
    ]
