# Generated by Django 5.1.2 on 2025-02-14 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterField(
            model_name='workorder',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='responsible_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.employee', verbose_name='Funcionário Responsável'),
        ),
    ]
