# Generated by Django 5.1.2 on 2024-12-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='impact',
            field=models.CharField(blank=True, choices=[('Baixo', 'Baixo'), ('Médio', 'Médio'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], max_length=25, null=True, verbose_name='Impacto'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Local do Serviço'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='priority',
            field=models.CharField(blank=True, choices=[('Baixo', 'Baixo'), ('Médio', 'Médio'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], max_length=25, null=True, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='requested_by',
            field=models.CharField(max_length=100, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título do Relato'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='urgency',
            field=models.CharField(blank=True, choices=[('Baixo', 'Baixo'), ('Médio', 'Médio'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], max_length=25, null=True, verbose_name='Urgência'),
        ),
    ]
