# Generated by Django 5.1.2 on 2025-02-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_category_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkorder',
            name='opening_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Data de Abertura'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='opening_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura'),
        ),
    ]
