# Generated by Django 5.1.2 on 2025-02-06 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_historicalworkorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkorder',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ordens/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Imagem'),
        ),
        migrations.DeleteModel(
            name='WorkOrderImage',
        ),
    ]
