# Generated by Django 5.1.2 on 2025-02-10 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_category_name_alter_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_date', models.DateTimeField(auto_now_add=True)),
                ('progress_description', models.TextField(verbose_name='Descrição do Progresso')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.workorder', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Progresso da Ordem de Serviço',
                'verbose_name_plural': 'Progressos das Ordens de Serviço',
                'ordering': ['-progress_date'],
            },
        ),
    ]
